Repository ita-social-projects/OoS-Frontend, pull requests merged in 2022-07, with the labels that each got.

#1420 About portal, Support, Rules
  src/app/header/header.component.html
  src/app/shared/services/platform/platform.service.ts
  src/app/shared/store/admin.actions.ts
  src/app/shared/store/admin.state.ts
  src/app/shared/styles/info.scss
  src/app/shell/admin-tools/platform/platform-info/info-edit/info-edit.component.html
  src/app/shell/admin-tools/platform/platform-info/info-edit/info-edit.component.ts
  src/app/shell/info/about/about.component.html
  src/app/shell/info/about/about.component.spec.ts
  src/app/shell/info/about/about.component.ts
  src/app/shell/info/rules/rules.component.html
  src/app/shell/info/rules/rules.component.ts
  src/app/shell/info/support/support.component.html
  src/app/shell/info/support/support.component.ts
Labels: ui

#1452 Remove the search bar in the "popular directions" page #1423
  src/app/shell/all-categories/all-categories.component.html
Labels: ui, bug:fixed

#1393 Fixed default value in the field Статуc
  src/app/shared/components/provider-info/provider-info.component.html
  src/app/shared/components/provider-info/provider-info.component.ts
  src/app/shared/constants/constants.ts
  src/app/shared/models/institutionStatus.model.ts
  src/app/shared/store/meta-data.state.ts
  src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.html
  src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.ts
Labels: bug
